CREATE TABLE `CAD_DEPARTAMENTO` (
  `ID_DEPARTAMENTO` int PRIMARY KEY,
  `DEP_NOME` varchar(150)
);

CREATE TABLE `CAD_CARGO` (
  `ID_CARGO` int PRIMARY KEY,
  `CARGO_NOME` varchar(150)
);

CREATE TABLE `CAD_FUNCIONARIO` (
  `ID_USUARIO` int PRIMARY KEY,
  `USU_NOME` varchar(200),
  `USU_DEPARTAMENTO` int,
  `USU_CARGO` int,
  `USU_DATACADASTRO` date,
  `USU_CPF` varchar(14),
  `USU_CNPJ` varchar(18),
  `USU_SENHA` varchar(255),
  `USU_STATUS` char(1)
);

CREATE TABLE `CAD_ANIMAL` (
  `ID_ANIMAL` int PRIMARY KEY,
  `ANI_NOME` varchar(150),
  `ANI_APELIDO` varchar(150)
);

CREATE TABLE `CAD_CLIENTE` (
  `ID_CLIENTE` int PRIMARY KEY,
  `CLI_NOME` varchar(150),
  `CLI_ANIMAL` int,
  `CLI_CPF` varchar(14),
  `CLI_CNPJ` varchar(18),
  `CLI_LOGRADOURO` varchar(150),
  `CLI_NUMERO` varchar(20),
  `CLI_COMPLEMENTO` varchar(40),
  `CLI_BAIRRO` varchar(40),
  `CLI_CIDADE` varchar(40),
  `CLI_ESTADO` char(2),
  `CLI_DATA` date,
  `CLI_STATUS` char(2),
  `CLI_HISTORICO` int
);

CREATE TABLE `CAD_PRODUTO` (
  `ID_PRODUTO` int PRIMARY KEY,
  `PRO_NOME` varchar(250),
  `PRO_CODIGOAUXILIAR` varchar(150),
  `PRO_QUANTIDADE` float,
  `PRO_UNIDADE` char(2),
  `PRO_STATUS` char(1)
);

CREATE TABLE `CAD_SERVICOS` (
  `ID_SERVICOS` int PRIMARY KEY,
  `SER_NOME` varchar(150),
  `SER_STATUS` char(1)
);

CREATE TABLE `MOV_ATENDIMENTO` (
  `ID_ATENDIMENTO` int PRIMARY KEY,
  `ATEND_TIPO` int,
  `ATEND_CLIENTE` int,
  `ATEND_DATA` datetime,
  `ATEND_FUNCIONARIO` int,
  `ATEND_RESPONSAVEL` int,
  `ATEND_DESCRICAO` text,
  `ATEND_PRODUTOS` int,
  `ATEND_VALOR` decimal(10,2)
);

CREATE TABLE `MOV_AGENDAMENTO` (
  `ID_AGENDAMENTO` int PRIMARY KEY,
  `AGEN_CLIENTE` int,
  `AGEN_DATA` date,
  `AGEN_HORA` time,
  `AGEN_DESCRICAO` varchar(400),
  `AGEN_RESPONSAVEL` int
);

ALTER TABLE `CAD_FUNCIONARIO` ADD FOREIGN KEY (`USU_DEPARTAMENTO`) REFERENCES `CAD_DEPARTAMENTO` (`ID_DEPARTAMENTO`);

ALTER TABLE `CAD_FUNCIONARIO` ADD FOREIGN KEY (`USU_CARGO`) REFERENCES `CAD_CARGO` (`ID_CARGO`);

ALTER TABLE `CAD_CLIENTE` ADD FOREIGN KEY (`CLI_ANIMAL`) REFERENCES `CAD_ANIMAL` (`ID_ANIMAL`);

ALTER TABLE `CAD_CLIENTE` ADD FOREIGN KEY (`CLI_HISTORICO`) REFERENCES `MOV_ATENDIMENTO` (`ID_ATENDIMENTO`);

ALTER TABLE `MOV_ATENDIMENTO` ADD FOREIGN KEY (`ATEND_TIPO`) REFERENCES `CAD_SERVICOS` (`ID_SERVICOS`);

ALTER TABLE `MOV_ATENDIMENTO` ADD FOREIGN KEY (`ATEND_CLIENTE`) REFERENCES `CAD_CLIENTE` (`ID_CLIENTE`);

ALTER TABLE `MOV_ATENDIMENTO` ADD FOREIGN KEY (`ATEND_FUNCIONARIO`) REFERENCES `CAD_FUNCIONARIO` (`ID_USUARIO`);

ALTER TABLE `MOV_ATENDIMENTO` ADD FOREIGN KEY (`ATEND_RESPONSAVEL`) REFERENCES `CAD_FUNCIONARIO` (`ID_USUARIO`);

ALTER TABLE `MOV_ATENDIMENTO` ADD FOREIGN KEY (`ATEND_PRODUTOS`) REFERENCES `CAD_PRODUTO` (`ID_PRODUTO`);

ALTER TABLE `MOV_AGENDAMENTO` ADD FOREIGN KEY (`AGEN_CLIENTE`) REFERENCES `CAD_CLIENTE` (`ID_CLIENTE`);

ALTER TABLE `MOV_AGENDAMENTO` ADD FOREIGN KEY (`AGEN_RESPONSAVEL`) REFERENCES `CAD_FUNCIONARIO` (`ID_USUARIO`);
