-- Emerson de Carvalho

-- A Criação do banco de dados com o diagrama de execícios.

-- Criação do banco de dados

CREATE DATABASE PROJETOS
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

-- Criando Tabelas

CREATE TABLE CAD_INSTRUMENTO(
    ID_INSTRUMENTO INT AUTO_INCREMENT PRIMARY KEY,
    INST_NOME VARCHAR(100)
) DEFAULT CHARSET = utf8;

CREATE TABLE CAD_DEPARTAMENTO(
    ID_DEPARTAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    DEPART_NOME VARCHAR(100)
) DEFAULT CHARSET = utf8;

CREATE TABLE CAD_SUPERVISOR(
    ID_SUPERVISOR INT AUTO_INCREMENT PRIMARY KEY,
    DEPART_NOME VARCHAR(100),
    ID_USUARIO INT
) DEFAULT CHARSET = utf8;
--OBSERVAÇÃO: RODAR RELACIONAMENTO NO FINAL DOS COMANDOS.

CREATE TABLE CAD_USUARIO(
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(100),
    ID_SUPERVISOR INT,
    ID_DEPARTAMENTO INT
) DEFAULT CHARSET = utf8;
--OBSERVAÇÃO: RODAR RELACIONAMENTO NO FINAL DOS COMANDOS.

CREATE TABLE CAD_VEICULO(
    ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    VEIC_NOME VARCHAR(50),
    ID_USUARIO INT
)
--OBSERVAÇÃO: RODAR RELACIONAMENTO NO FINAL DOS COMANDOS.

CREATE TABLE MOV_PROJETOS(
    ID_PROJETO INT AUTO_INCREMENT PRIMARY KEY,
    PROJETO_NOME VARCHAR(80),
    ID_INSTRUMENTO INT,
    ID_USUARIO INT,
    ID_VEICULO INT,
    ID_DEPARTAMENTO INT
)
--OBSERVAÇÃO: RODAR RELACIONAMENTO NO FINAL DOS COMANDOS.

-- Adicionando as FK

ALTER TABLE CAD_SUPERVISOR
ADD CONSTRAINT FK_SUPERVISOR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES CAD_USUARIO(ID_USUARIO)

ALTER TABLE CAD_USUARIO
ADD CONSTRAINT FK_USUARIO_SUPERVISOR FOREIGN KEY (ID_SUPERVISOR) REFERENCES CAD_SUPERVISOR(ID_SUPERVISOR),
ADD CONSTRAINT FK_USUARIO_DEPARTEMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES CAD_DEPARTAMENTO(ID_DEPARTAMENTO)

ALTER TABLE CAD_VEICULO
ADD CONSTRAINT FK_VEICULO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES CAD_USUARIO(ID_USUARIO)

ALTER TABLE MOV_PROJETOS
ADD CONSTRAINT FK_PROJETOS_INSTRUMENTO FOREIGN KEY (ID_INSTRUMENTO) REFERENCES CAD_INSTRUMENTO (ID_INSTRUMENTO),
ADD CONSTRAINT FK_PROJETOS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES CAD_USUARIO (ID_USUARIO),
ADD CONSTRAINT FK_PROJETOS_VEICULO FOREIGN KEY (ID_VEICULO) REFERENCES CAD_VEICULO (ID_VEICULO),
ADD CONSTRAINT FK_PROJETOS_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES CAD_DEPARTAMENTO (ID_DEPARTAMENTO)

-- Inserindo dados no banco com FK

INSERT INTO CAD_INSTRUMENTO (INST_NOME) 
VALUES ('Bisturis'), ('Tesouras'), ('Pinças')

INSERT INTO CAD_DEPARTAMENTO (DEPART_NOME)
VALUES ('Centro Cirúrgico'), ('Centro de Materiais e Esterilização'), ('Sala de Recuperação Pós-Anestésica')

INSERT INTO CAD_SUPERVISOR (DEPART_NOME)
VALUES ('cirurgião-chefe'), ('coordenador cirúrgico'), ('Supervisor de Programa')

INSERT INTO CAD_USUARIO (USU_NOME, ID_SUPERVISOR, ID_DEPARTAMENTO)
VALUES ('Emerson de Carvalho', 4, 1), ('Eduardo Fernander', 5, 3), ('Kadu Fernandes', 6, 1)

UPDATE CAD_USUARIO SET ID_DEPARTAMENTO = 1 WHERE ID_USUARIO = 4;
UPDATE CAD_USUARIO SET ID_DEPARTAMENTO = 2 WHERE ID_USUARIO = 5;
UPDATE CAD_USUARIO SET ID_DEPARTAMENTO = 3 WHERE ID_USUARIO = 6;

INSERT INTO CAD_VEICULO (VEIC_NOME, ID_USUARIO)
VALUES ('Ambulância', 4), ('Carro', 5), ('Van', 6)

INSERT INTO MOV_PROJETOS (PROJETO_NOME, ID_INSTRUMENTO, ID_USUARIO, ID_VEICULO, ID_DEPARTAMENTO)
VALUES ('Cirurgia Neurológica', 1, 4, 1, 1), ('Cirurgia Cardíaca', 2, 5, 2, 2), ('Cirurgia Ortopédica', 3, 6, 3, 3)

