SELECT * FROM TB_RESERVA_SALA
INNER JOIN TB_SALA ON TB_RESERVA_SALA.SALA_ID = TB_SALA.ID


SELECT TB_SALA.ID, TB_RESERVA_SALA.ID  FROM TB_RESERVA_SALA
INNER JOIN TB_SALA ON TB_RESERVA_SALA.SALA_ID = TB_SALA.ID